--- ex. 01
select NAME 
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME, 3), id

--- EX. 02
SELECT USER_ID,
CONCAT(UPPER(LEFT(NAME,1)),LOWER(RIGHT(NAME, LENGTH(NAME)-1))) AS NAME
FROM USERS 

--- EX. 03 
SELECT MANUFACTURER,
ROUND(SUM(TOTAL_SALES)/1000000,0) AS SALE
FROM pharmacy_sales
GROUP BY MANUFACTURER

--- EX. 04 
