--- ex. 01
select NAME 
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME, 3), id

--- EX. 02
SELECT USER_ID,
CONCAT(UPPER(LEFT(NAME,1)),LOWER(RIGHT(NAME, LENGTH(NAME)-1))) AS NAME
FROM USERS 

--- EX. 03 
SELECT MANUFACTURER,
'$'|| ROUND(SUM(TOTAL_SALES)/1000000,0)||'MILLIONS' AS SALE
FROM pharmacy_sales
GROUP BY MANUFACTURER

--- EX. 04 
SELECT
PRODUCT_ID,
EXTRACT(MONTH FROM SUBMIT_DATE) AS MONTH,
ROUND(AVG(STARS),2)
FROM reviews
GROUP BY EXTRACT(MONTH FROM SUBMIT_DATE), PRODUCT_ID
ORDER BY EXTRACT(MONTH FROM SUBMIT_DATE), PRODUCT_ID

--- EX. 05
SELECT SENDER_ID,
COUNT(MESSAGE_ID) AS TIMES 
FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE) = 8 AND EXTRACT(YEAR FROM SENT_DATE)=2022
GROUP BY SENDER_ID
ORDER BY TIMES DESC
LIMIT 2

--- EX. 06
SELECT TWEET_ID
FROM TWEETS 
WHERE LENGTH(CONTENT) >15

--- EX. 07
SELECT ACTIVITY_DATE,
COUNT(DISTINCT USER_ID) AS ACTIVE_USER
FROM ACTIVITY
WHERE  activity_date BETWEEN '2019-06-27' AND '2019-07-27'
GROUP BY ACTIVITY_DATE

--- EX. 08
select 
COUNT (ID) 
from employees 
WHERE EXTRACT(MONTH FROM JOINING_DATE) BETWEEN 1 AND 7 
AND EXTRACT(YEAR FROM JOINING_DATE) =2022

--- EX. 09
select 
POSITION ('a' in FIRST_NAME) 
from worker
WHERE FIRST_NAME = 'Amitah'

--- EX. 10
select 
SUBSTRING (TITLE,LENGTH(WINERY) +2, 4)
from winemag_p2




