--- EX. 1
SELECT DISTINCT CITY FROM STATION 
WHERE ID%2=0

--- EX. 2
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION

/* EX. 3 
round it up to the next integer = CEILING
REPLACE(SALARY,0,''): THAY THẾ MỘT CHUỖI NHỎ/KÝ TỰ TRONG MỘT CHUỖI LỚN BẰNG CHUỐI/KÝ TỰ KHÁC*/ 
  
SELECT 
CEILING(AVG(SALARY)- AVG(REPLACE(SALARY,0,'')))
FROM EMPLOYEES

